### ISSUE TITLE
Integrate calendar

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte-website#21]
Right now we are using a Google Calendar for events.
It would be nice to have it on the website with an automatic timezone selector.

For reference, here is the embed code, the embed URL, and a simple URL.

```html
<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=UTC&showNav=1&showTitle=1&showTz=1&showPrint=0&showCalendars=0&src=NTJoMzg5NTEzdnQ3YWZnMDFtNTZicTlsMjhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&color=%23E67C73" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

```
https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=UTC&showNav=1&showTitle=1&showTz=1&showPrint=0&showCalendars=0&src=NTJoMzg5NTEzdnQ3YWZnMDFtNTZicTlsMjhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&color=%23E67C73
```

```
https://calendar.google.com/calendar/embed?src=52h389513vt7afg01m56bq9l28%40group.calendar.google.com
```

**Comment by IF-Adin** [comment]
Integrating any google services raises problem with privacy and will significantly increase page loading times. I'd recommend rather using a local calendar application.

**Comment by JulianGro** [comment]
Yeah I am up for any suggestions.
Last time I looked for an alternative I wasn't able to find anything that got the work done.

**Comment by Kreolis** [comment]
https://calendar.overte.org/
